source 'https://rubygems.org'

gem 'html-pipeline', '1.9.0'
gem 'asciidoctor', '0.1.4'
gem 'gemoji', '~> 1.0'
gem 'rinku', '~> 1.7'
gem 'sanitize', '~> 2.0'
if RUBY_VERSION < '2.1.0'
  gem 'github-linguist', '~> 2.6.2'
else
  gem 'github-linguist', '~> 2.10'
end
